packages/ext-components-kitchensink/src/app.js, packages/ext-components-kitchensink/src/index.html, packages/ext-components-kitchensink/src/view/components/carousel/CarouselComponent.css, packages/ext-components-kitchensink/src/view/components/carousel/CarouselComponent.html, packages/ext-components-kitchensink/src/view/components/carousel/CarouselComponent.js
In this PR, Carousel Component has been added.
=> EWC-4-Created carousel component

packages/ext-components-kitchensink/src/app.js, packages/ext-components-kitchensink/src/view/components/drag&drop/constraints/ConstraintsDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/constraints/ConstraintsDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/constraints/ConstraintsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/data/DataDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/data/DataDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/data/DataDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/files/FilesDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/files/FilesDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/files/FilesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/groups/GroupsDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/groups/GroupsDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/groups/GroupsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/handles/HandlesDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/handles/HandlesDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/handles/HandlesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/proxies/ProxiesDragDropComponent.css, packages/ext-components-kitchensink/src/view/components/drag&drop/proxies/ProxiesDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/proxies/ProxiesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/simple/SimpleDragDropComponent.html, packages/ext-components-kitchensink/src/view/components/drag&drop/simple/SimpleDragDropComponent.js
All the Drag & Drop Component has been added in this PR.
=> EWC-4 KitchenSink app Drag Drop all components are added.

packages/ext-components-kitchensink/src/view/components/drag&drop/constraints/ConstraintsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/data/DataDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/files/FilesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/groups/GroupsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/handles/HandlesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/proxies/ProxiesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/simple/SimpleDragDropComponent.js
Imported .html file in .js file to make hot reload working if we do changes in html files.
=> EWC-4-KS-ParentComp-DragDrop | Make Hot Reload working for html

packages/ext-components-kitchensink/src/app.js, packages/ext-components-kitchensink/src/view/components/draw/DrawComponent.html, packages/ext-components-kitchensink/src/view/components/draw/DrawComponent.js
In this PR Draw component is working fine, issue related to the HTML inside container pertains leading to an unwanted design in the UI.
=> EWC-4-KS-ParentComp-Draw2 | Added Draw Component

packages/ext-components-kitchensink/src/app.js, packages/ext-components-kitchensink/src/view/components/layouts/card/CardLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/card/CardLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/center/CenterLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/center/CenterLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/fit/FitLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/fit/FitLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/form/FormLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/form/FormLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/hbox/hboxLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/hbox/hboxLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/resizable/ResizableLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/resizable/ResizableLayoutComponent.js, packages/ext-components-kitchensink/src/view/components/layouts/vbox/vboxLayoutComponent.css, packages/ext-components-kitchensink/src/view/components/layouts/vbox/vboxLayoutComponent.html, packages/ext-components-kitchensink/src/view/components/layouts/vbox/vboxLayoutComponent.js, packages/ext-components-kitchensink/src/view/main/MainComponent.html
In this PR all the components of layout are done except hbox,vbox component in which scroll is not working and card layout is remaining.
=> EWC-4-KS-Components-Layouts | done all layout components except hbox,vbox and card layout

packages/ext-components-kitchensink/src/view/components/drag&drop/constraints/ConstraintsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/data/DataDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/files/FilesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/groups/GroupsDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/handles/HandlesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/proxies/ProxiesDragDropComponent.js, packages/ext-components-kitchensink/src/view/components/drag&drop/simple/SimpleDragDropComponent.js
All the arrow from functions are removed in this PR.
=> EWC-4-KS-ParentComp-DragDrop | removed arrow from functions

packages/ext-components-kitchensink/src/view/components/draw/DrawComponent.js
In this PR bind issue has been resolved.
=> EWC-4-ParentComp-Draw | resolved bind issue in draw component

packages/ext-components-kitchensink/src/view/components/touchevents/TouchEventsComponent.html, packages/ext-components-kitchensink/src/view/components/touchevents/TouchEventsComponent.js
In this PR Touch event component has been completed.
=> EWC-4-KS-Components-TouchEvents | completed touch events component

packages/ext-components-kitchensink/src/view/components/progressbar/ProgressBarComponent.js, packages/ext-components-kitchensink/src/view/components/sheet/SheetComponent.js, packages/ext-components-kitchensink/src/view/components/titlebar/TitleBarComponent.html, packages/ext-components-kitchensink/src/view/components/titlebar/TitleBarComponent.js
completed the titlebar component.
=> titlebar completed

packages/ext-components-kitchensink/src/view/components/sheet/SheetComponent.html, packages/ext-components-kitchensink/src/view/components/sheet/SheetComponent.js
In this task, the issue related to Sheet is now resolved. Sheet is now working similar to Ext React and Ext Angular Sheet.
Known Issue:
- setReveal(false) is not working. Also tried setReveal(null)
Kindly Review.
Rahul Garg
=> EWC-4-KS-Sheet

packages/ext-components-kitchensink/src/view/grids/corefeatures/groupedgrid/GroupedGridComponent.css, packages/ext-components-kitchensink/src/view/grids/corefeatures/groupedgrid/GroupedGridComponent.html, packages/ext-components-kitchensink/src/view/grids/corefeatures/groupedgrid/GroupedGridComponent.js, packages/ext-components-kitchensink/src/view/grids/corefeatures/groupedgrid/RestaurantData.js
In this PR, Group Grid is completed.
Kindly Review,
Rahul Garg
=> EWC-4 Kitchensink Grouped Grid

packages/ext-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponent.css, packages/ext-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponent.html, packages/ext-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponent.js, packages/ext-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponentData.js, packages/ext-components-kitchensink/src/view/charts/area/fullstackedarea/FullStackedAreaComponent.css, packages/ext-components-kitchensink/src/view/charts/area/fullstackedarea/FullStackedAreaComponent.html, packages/ext-components-kitchensink/src/view/charts/area/fullstackedarea/FullStackedAreaComponent.js, packages/ext-components-kitchensink/src/view/charts/area/negativevaluesarea/NegativeValuesAreaComponent.css, packages/ext-components-kitchensink/src/view/charts/area/negativevaluesarea/NegativeValuesAreaComponent.html, packages/ext-components-kitchensink/src/view/charts/area/negativevaluesarea/NegativeValuesAreaComponent.js, packages/ext-components-kitchensink/src/view/charts/area/stackedarea/StackedAreaComponent.css, packages/ext-components-kitchensink/src/view/charts/area/stackedarea/StackedAreaComponent.html, packages/ext-components-kitchensink/src/view/charts/area/stackedarea/StackedAreaComponent.js, packages/ext-components-kitchensink/src/view/charts/charttoolbar/ChartToolbar.js
Hello Marc,
This is the replication of the issue I was facing yesterday as well for the reference, In this PR, sub components of area have been added but the issue is I am unable to add an event listener on the child buttons of ChartToolbar.js file.
Kindly suggest how I can attach an event(click or tap) on the same.
For reference please check following files:
1. BasicAreaComponent.html (line 14: Chart toolbar is used.) Full path: _view/charts/area/basicarea/BasicAreaComponent.html_
2. ChartToolbar.js (line 143: Handler is called but not working also tried onTap.) Full path: 
_view/charts/charttoolbar/ChartToolbar.js_
Waiting for the response. Kindly suggest.
Thanks
Palak Rathi.
=> EWC-4-KS-Added all sub components of area.

packages/ext-components-kitchensink/src/menu.js, packages/ext-components-kitchensink/src/view/charts/bar/basicbar/BasicBarComponent.css, packages/ext-components-kitchensink/src/view/charts/bar/basicbar/BasicBarComponent.html, packages/ext-components-kitchensink/src/view/charts/bar/basicbar/BasicBarComponent.js, packages/ext-components-kitchensink/src/view/charts/bar/fullstackedbar/FullStackedBarComponent.css, packages/ext-components-kitchensink/src/view/charts/bar/fullstackedbar/FullStackedBarComponent.html, packages/ext-components-kitchensink/src/view/charts/bar/fullstackedbar/FullStackedBarComponent.js, packages/ext-components-kitchensink/src/view/charts/bar/stackedbar/StackedBarComponent.css, packages/ext-components-kitchensink/src/view/charts/bar/stackedbar/StackedBarComponent.html, packages/ext-components-kitchensink/src/view/charts/bar/stackedbar/StackedBarComponent.js, packages/ext-components-kitchensink/src/view/charts/bar/stackedbar/StackedBarComponentData.js, packages/ext-components-kitchensink/src/view/charts/charttoolbar/ChartToolbar.js
Hi Marc,
In this PR, I have completed Bars.
Kindly review & merge.
Thanks,
Palak
=> EWC-4-Completed bars

packages/ext-components-kitchensink/src/view/charts/boxplot/BoxPlotComponent.css, packages/ext-components-kitchensink/src/view/charts/boxplot/BoxPlotComponent.html, packages/ext-components-kitchensink/src/view/charts/boxplot/BoxPlotComponent.js, packages/ext-components-kitchensink/src/view/charts/boxplot/BoxPlotComponentData.js, packages/ext-components-kitchensink/src/view/charts/charttoolbar/ChartToolbar.js
Hi Marc,
I have completed boxplot in this PR.
Kindly review & merge.
Thanks,
Palak
=> EWC-4-KS-completed boxplot.

packages/ext-web-components-tests/package.json, packages/ext-web-components-tests/src/app.js, packages/ext-web-components-tests/src/view/attributeupdate/classnameupdate/ClassNameUpdateComponent.js, packages/ext-web-components-tests/src/view/attributeupdate/simpleattributeupdate/SimpleAttributeUpdateComponent.js, packages/ext-web-components-tests/src/view/createChild/elementinsertbetween/ElementInsertBetweenComponent.js, packages/ext-web-components-tests/src/view/createChild/elementinsertend/ElementInsertEndComponent.js, packages/ext-web-components-tests/src/view/createChild/insertbetween/InsertBetweenComponent.js, packages/ext-web-components-tests/src/view/createChild/insertend/InsertEndComponent.js, packages/ext-web-components-tests/src/view/event/basicevent/BasicEventComponent.js, packages/ext-web-components-tests/src/view/lifecycle/LifecycleComponent.js, packages/ext-web-components-tests/src/view/main/MainComponent.html, packages/ext-web-components-tests/src/view/main/MainComponent.js, packages/ext-web-components-tests/src/view/rel/reldialog/RelDialogComponent.js, packages/ext-web-components-tests/src/view/updatefunctions/UpdateFunctionsComponent.html, packages/ext-web-components-tests/src/view/updatefunctions/UpdateFunctionsComponent.js, packages/ext-web-components-tests/webpack.config.js
New PR with the updated code as per the changes in the bridge.
Kindly Review
Rahul Garg
=> EWC-2-H New PR for the new changes in the Bridge.

packages/ext-web-components-tests/.eslintignore, packages/ext-web-components-tests/.eslintrc, packages/ext-web-components-tests/src/app.js, packages/ext-web-components-tests/src/helper/responsiveFormulas.js, packages/ext-web-components-tests/src/menu.js, packages/ext-web-components-tests/src/view/attributeupdate/classnameupdate/ClassNameUpdateComponent.js, packages/ext-web-components-tests/src/view/attributeupdate/simpleattributeupdate/SimpleAttributeUpdateComponent.js, packages/ext-web-components-tests/src/view/createChild/elementinsertbetween/ElementInsertBetweenComponent.js, packages/ext-web-components-tests/src/view/createChild/elementinsertend/ElementInsertEndComponent.js, packages/ext-web-components-tests/src/view/createChild/elementinsertstart/ElementInsertStartComponent.js, packages/ext-web-components-tests/src/view/createChild/insertbetween/InsertBetweenComponent.js, packages/ext-web-components-tests/src/view/createChild/insertend/InsertEndComponent.js, packages/ext-web-components-tests/src/view/createChild/insertstart/InsertStartComponent.js, packages/ext-web-components-tests/src/view/defaults/DefaultsComponent.js, packages/ext-web-components-tests/src/view/event/basicevent/BasicEventComponent.js, packages/ext-web-components-tests/src/view/event/singleevent/SingleEventComponent.js, packages/ext-web-components-tests/src/view/html/HtmlComponent.js, packages/ext-web-components-tests/src/view/lifecycle/LifecycleComponent.js, packages/ext-web-components-tests/src/view/lifecycle/MyComponent.js, packages/ext-web-components-tests/src/view/main/MainComponent.js, packages/ext-web-components-tests/src/view/rel/rel/RelComponent.js, packages/ext-web-components-tests/src/view/rel/reldialog/RelDialogComponent.js, packages/ext-web-components-tests/src/view/rel/releditor/RelEditorComponent.js, packages/ext-web-components-tests/src/view/rel/relgridcolumn/RelGridColumnComponent.js, packages/ext-web-components-tests/src/view/rel/relmenu/RelMenuComponent.js, packages/ext-web-components-tests/src/view/rel/reltooltip/RelTooltipComponent.js, packages/ext-web-components-tests/src/view/senchatesthooks/SenchaTestHooksComponent.js, packages/ext-web-components-tests/src/view/simple/SimpleComponent.js, packages/ext-web-components-tests/src/view/updatefunctions/UpdateFunctionsComponent.js
In this PR, eslint has been implemented in ext-web-components-tests.
=> EWC-4-H-Test-Lint | Implement eslint on ext-web-components-tests

packages/ext-web-components-kitchensink/src/view/grids/add-ons/summaryrow/SummaryRowComponent.html
This is a small bug fix of Summary Row Grid.
Kindly Review
Rahul Garg
=> EWC-4-KS Summary Row Fix

packages/ext-web-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponent.html, packages/ext-web-components-kitchensink/src/view/charts/area/basicarea/BasicAreaComponent.js, packages/ext-web-components-kitchensink/src/view/charts/area/fullstackedarea/FullStackedAreaComponent.html, packages/ext-web-components-kitchensink/src/view/charts/area/fullstackedarea/FullStackedAreaComponent.js, packages/ext-web-components-kitchensink/src/view/charts/area/negativevaluesarea/NegativeValuesAreaComponent.html, packages/ext-web-components-kitchensink/src/view/charts/area/negativevaluesarea/NegativeValuesAreaComponent.js, packages/ext-web-components-kitchensink/src/view/charts/area/stackedarea/StackedAreaComponent.html, packages/ext-web-components-kitchensink/src/view/charts/area/stackedarea/StackedAreaComponent.js, packages/ext-web-components-kitchensink/src/view/charts/chartgauges/basicgaugechart/BasicGaugeChartComponent.js, packages/ext-web-components-kitchensink/src/view/charts/column/basiccolumn/BasicColumnComponent.js, packages/ext-web-components-kitchensink/src/view/charts/line/plot/PlotComponent.html, packages/ext-web-components-kitchensink/src/view/charts/line/plot/PlotComponent.js, packages/ext-web-components-kitchensink/src/view/charts/line/realtime/RealtimeComponent.html, packages/ext-web-components-kitchensink/src/view/charts/line/realtime/RealtimeComponent.js, packages/ext-web-components-kitchensink/src/view/charts/line/spline/SplineComponent.html, packages/ext-web-components-kitchensink/src/view/charts/line/spline/SplineComponent.js, packages/ext-web-components-kitchensink/src/view/charts/line/splinemarkers/SplineMarkersComponent.html, packages/ext-web-components-kitchensink/src/view/charts/line/splinemarkers/SplineMarkersComponent.js, packages/ext-web-components-kitchensink/src/view/charts/navigation/NavigationComponent.js, packages/ext-web-components-kitchensink/src/view/charts/pie/basicpie/BasicPieComponent.js, packages/ext-web-components-kitchensink/src/view/charts/pie/donut/DonutComponent.js, packages/ext-web-components-kitchensink/src/view/charts/pie/doubledonut/DoubleDonutComponent.js, packages/ext-web-components-kitchensink/src/view/charts/pie/spie/SpieComponent.js, packages/ext-web-components-kitchensink/src/view/charts/pie/threedpie/ThreeDPieComponent.js, packages/ext-web-components-kitchensink/src/view/charts/radar/basicradar/BasicRadarComponent.js, packages/ext-web-components-kitchensink/src/view/charts/radar/filled/FilledComponent.js, packages/ext-web-components-kitchensink/src/view/charts/radar/marked/MarkedComponent.js
Hi Marc,
I have renamed variables in charts folder. Kindly review and merge.
Thanks,
Palak
=> Renamed Charts folder

packages/ext-web-components-tests/src/view/rel/releditor/RelEditorComponent.html, packages/ext-web-components-tests/src/view/rel/relgridcolumn/RelGridColumnComponent.html, packages/ext-web-components-tests/test/AllTests/rel/relcolumn.js, packages/ext-web-components-tests/test/AllTests/rel/releditor.js
Hello Marc,
Test cases for Nested Columns and Editors are added. They are currently failing.
Kindly Review
Rahul Garg
=> EWC-2-Test-Cases

api-docs/modern/modern/src/MessageBox.js, api-docs/modern/modern/src/Panel.js, api-docs/modern/modern/src/layout/Fit.js, api-docs/modern/modern/src/layout/Form.js, api-docs/modern/modern/src/layout/HBox.js, api-docs/modern/modern/src/layout/VBox.js, api-docs/modern/modern/src/menu/CheckItem.js, api-docs/modern/modern/src/menu/Item.js, api-docs/modern/modern/src/menu/Menu.js, api-docs/modern/modern/src/menu/RadioItem.js, api-docs/modern/modern/src/panel/Time.js, api-docs/modern/modern/src/tab/Panel.js, packages/ext-web-components-kitchensink/src/menu.js, packages/ext-web-components-kitchensink/src/view/trees/treereorder/TreeReorderComponent.html, packages/ext-web-components-kitchensink/src/view/trees/treereorder/TreeReorderComponent.js, packages/ext-web-components-kitchensink/src/view/trees/treereorder/data.js
In this PR, api docs of following kitchensink components has been completed:-
- Fit
- Form
- HBox
- VBox
- CheckItem
- Item
- Menu
- RadioItem
- MessageBox
- Panel(tab)
- Time
=> EWC-5-api-docs-3 | Completed Api Docs

api-docs/modern/modern/src/Button.js, api-docs/modern/modern/src/Dialog.js, api-docs/modern/modern/src/dataview/IndexBar.js, api-docs/modern/modern/src/dataview/List.js, api-docs/modern/modern/src/dataview/NestedList.js, api-docs/modern/modern/src/field/Checkbox.js, api-docs/modern/modern/src/field/ComboBox.js, api-docs/modern/modern/src/field/Date.js, api-docs/modern/modern/src/field/Email.js, api-docs/modern/modern/src/field/File.js, api-docs/modern/modern/src/field/Hidden.js, api-docs/modern/modern/src/field/Number.js, api-docs/modern/modern/src/field/Password.js, api-docs/modern/modern/src/field/Radio.js, api-docs/modern/modern/src/field/Search.js, api-docs/modern/modern/src/field/Select.js, api-docs/modern/modern/src/field/Slider.js, api-docs/modern/modern/src/field/Spinner.js
This PR is focussed on EWC-5-Docs work. Fiddle examples of following components are completed under this PR:
1. IndexBar                                                                                      
2. List                                                                                           
3. NestedList                                                                                  
4. Dialog                                            
5. Checkbox                                       
6. ComboBox                                     
7. Button                                            
8. Spinner                                           
9. Date
10. Email
11. File 
12. Hidden
13. Number
14. Password
15. Radio
16. Search
17. Select
18. Slider
19. Text
=> EWC-5-APIDOCS-Example fiddle example docs

packages/ext-web-components-boilerplate/src/view/home/HomeComponent.html
Hello Marc,
There was a small issue with IE11 in the boilerplate which is resolved.
Kindly Review
Rahul Garg
=> EWC-2-Boilerplate IE 11 Fix

packages/ext-web-components-kitchensink/src/view/trees/heterogeneoustree/HeterogeneousTreeComponent.js, packages/ext-web-components-kitchensink/src/view/trees/tree/TreeComponent.html
Mobile View of Tree component inside Trees categorization is fixed.
=> Ext-Web-Component-KitchenSink-BugFix: tree component mobile view is fixed

packages/ext-web-components-boilerplate/src/view/main/MainComponent.js
In this PR, the issue related to initially navbar open in mobile view has been resolved.
=> EWC-Boilerplate | Fixed Initially Navbar open issue in mobile view

packages/ext-web-components-kitchensink/src/menu.js, packages/ext-web-components-kitchensink/src/view/grids/add-ons/rowdraganddrop/RowDragAndDropComponent.html, packages/ext-web-components-kitchensink/src/view/grids/add-ons/rowdraganddrop/RowDragAndDropComponent.js
Hello Marc, Row Drag and Drop example of KS is now added inside the Web Component KS.
Kindly Review
Rahul Garg
=> EWC-4 | Row Drag and Drop

api-docs/modern/modern/src/Button.js
I'd like to test the generator and fiddle out.
=> Update @example spacing

api-docs/core/src/Progress.js, api-docs/modern/modern/src/ActionSheet.js, api-docs/modern/modern/src/Button.js, api-docs/modern/modern/src/carousel/Carousel.js, api-docs/modern/modern/src/field/ComboBox.js, api-docs/modern/modern/src/field/File.js, api-docs/modern/modern/src/field/Hidden.js, api-docs/modern/modern/src/field/Number.js, api-docs/modern/modern/src/field/Password.js, api-docs/modern/modern/src/field/Search.js, api-docs/modern/modern/src/field/Select.js, api-docs/modern/modern/src/field/Slider.js, api-docs/modern/modern/src/layout/Form.js
This PR is focused over Closing Tags Bug Fixes in Ext-Web-Component fiddle examples. Following Components are updated under this PR:
1. Progress
2. ActionSheet
3. Button
4. Carousel
5. ComboBox
6. File
7. Hidden
8. Number
9. Password
10. Search
11. Select
12. Slider
13. Form
=> Ext-Web-Component-ApiDocs-Bug-Fix | fiddle example docs Closing Tags Bug Fixes

packages/ext-web-components-kitchensink/src/view/calendar/calendarweekview/CalendarWeekViewComponent.js
Hello Marc,
Workweek view of Calendar component is fixed. Kindly review.
Thanks, Medha.
=> Calendar is fixed

api-docs/charts/src/draw/Container.js, api-docs/core/src/list/Tree.js, api-docs/modern/modern/src/Dialog.js, api-docs/modern/modern/src/MessageBox.js, api-docs/modern/modern/src/SplitButton.js, api-docs/modern/modern/src/Toast.js, api-docs/modern/modern/src/dataview/DataView.js, api-docs/modern/modern/src/dataview/IndexBar.js, api-docs/modern/modern/src/dataview/List.js, api-docs/modern/modern/src/dataview/NestedList.js, api-docs/modern/modern/src/field/ComboBox.js, api-docs/modern/modern/src/field/Date.js, api-docs/modern/modern/src/field/Search.js, api-docs/modern/modern/src/field/Select.js, api-docs/modern/modern/src/field/Slider.js, api-docs/modern/modern/src/grid/Grid.js, api-docs/modern/modern/src/grid/filters/Plugin.js, api-docs/modern/modern/src/grid/plugin/CellEditing.js, api-docs/modern/modern/src/grid/plugin/Editable.js, api-docs/modern/modern/src/grid/plugin/PagingToolbar.js, api-docs/modern/modern/src/grid/plugin/RowExpander.js, api-docs/modern/modern/src/grid/plugin/Summary.js, api-docs/modern/modern/src/grid/plugin/ViewOptions.js, api-docs/modern/modern/src/picker/Date.js, api-docs/modern/modern/src/picker/Picker.js, api-docs/ux/modern/src/colorpick/Button.js, api-docs/ux/modern/src/colorpick/Field.js, api-docs/ux/modern/src/colorpick/Selector.js
Hello Marc,
Changes are done in API-docs, kindly review.
Thanks, Medha Singh.
=> EWC-5 | Attaching component to the window object.

packages/ext-web-components-kitchensink/src/view/components/panels/resizablehandle/ResizableHandleComponent.html, packages/ext-web-components-kitchensink/src/view/grids/advancedfeatures/selectandcopy/SelectAndCopyComponent.js, packages/ext-web-components-kitchensink/src/view/grids/corefeatures/basicgrid/BasicGridComponent.html, packages/ext-web-components-kitchensink/src/view/grids/corefeatures/basicgrid/BasicGridComponent.js, packages/ext-web-components-kitchensink/src/view/pivotgrids/drilldownplugin/DrilldownPluginComponent.html, packages/ext-web-components-kitchensink/src/view/pivotgrids/drilldownplugin/DrilldownPluginComponent.js, packages/ext-web-components-kitchensink/src/view/pivotgrids/rangeeditorplugin/RangeEditorPluginComponent.html, packages/ext-web-components-kitchensink/src/view/pivotgrids/rangeeditorplugin/RangeEditorPluginComponent.js, packages/ext-web-components-kitchensink/src/view/trees/heterogeneoustree/HeterogeneousTreeComponent.html, packages/ext-web-components-kitchensink/src/view/trees/treelist/TreeListComponent.js, packages/ext-web-components-kitchensink/src/view/trees/treelist/data.js
In this PR, Grids and Pivot Grids Component's Bugs of latest QA bug cycle has been fixed.
=> EWC-KS-LatestBugFixes | Fixed Grids and Pivot Grids Component Bugs

packages/ext-web-components-kitchensink/src/view/components/froalaeditor/FroalaEditorComponent.js
In this PR, the example of Froala editor is updated as per ExtJs 7.0 Modern Example.
=> EWC-4-KS | Updated Froala Editor.

packages/ext-web-components-kitchensink/src/index.js, packages/ext-web-components-kitchensink/src/view/components/layouts/accordionlayout/AccordionLayoutComponent.html, packages/ext-web-components-kitchensink/src/view/components/lists/disclosurelist/DisclosureListComponent.js, packages/ext-web-components-kitchensink/src/view/grids/advancedfeatures/selectandcopy/SelectAndCopyComponent.js
This PR comprises work related to IE bugs.
Kindly Review
Rahul Garg
=> EWC-4 | KS IE Related bugs are fixed.

packages/ext-web-components-kitchensink/src/view/grids/add-ons/dragformtogrid/DragFormToGridComponent.js
In this PR, DragFormToGrid Component bug coming in mozilla firefox browser has been fixed.
=> EWC-KS-LatestBugFixed | DragFormToGrid Component bug fixed

api-docs/charts/src/draw/Container.js, api-docs/core/src/list/Tree.js, api-docs/modern/modern/src/dataview/DataView.js, api-docs/modern/modern/src/dataview/IndexBar.js, api-docs/modern/modern/src/dataview/NestedList.js, api-docs/modern/modern/src/field/Checkbox.js
Hi Marc
In this PR following fiddle examples are fixed:
1. Container
2. Tree
3. DataView
4. IndexBar
5. NestedList
6. Checkbox
Kindly review.
Thanks
Pooja
=> EWC-5-ApiDocs-Fiddle-Example-Fixes | ext-web-component api docs examples bug fixes

api-docs/modern/modern/src/MessageBox.js, api-docs/modern/modern/src/Panel.js, api-docs/modern/modern/src/SplitButton.js, api-docs/modern/modern/src/Toast.js, api-docs/modern/modern/src/field/Date.js, api-docs/modern/modern/src/menu/Item.js, api-docs/modern/modern/src/menu/Menu.js, api-docs/modern/modern/src/menu/RadioItem.js, api-docs/modern/modern/src/panel/Time.js, api-docs/modern/modern/src/picker/Date.js, api-docs/modern/modern/src/picker/Picker.js, api-docs/modern/modern/src/tab/Panel.js, api-docs/ux/modern/src/colorpick/Field.js, packages/ext-web-components-conference-app/src/view/schedule/ScheduleComponent.html
Hi Marc,
In this PR examples are fixed.
Thanks,
Medha
=> EWC-5 fiddle example fix

api-docs/modern/modern/src/field/Hidden.js, api-docs/modern/modern/src/field/Select.js, api-docs/modern/modern/src/field/Slider.js, api-docs/modern/modern/src/field/Text.js
Hello Marc,
In this PR, examples in api-docs have been fixed.
Kindly review and merge.
Thanks,
Palak
=> EWC-5-Fixed the bugs in 4 files.

api-docs/modern/modern/src/tab/Bar.js, api-docs/modern/modern/src/tab/Tab.js
Hi Marc,
Fixed a few components of API docs.
Thanks, Medha.
=> fixed api docs

packages/ext-web-components-kitchensink/src/view/components/forms/validation/ValidationComponent.html, packages/ext-web-components-kitchensink/src/view/components/forms/validation/ValidationComponent.js, packages/ext-web-components-kitchensink/src/view/d3/heatmap/configurablepivotheatmap/ConfigurablePivotHeatmapComponent.js, packages/ext-web-components-kitchensink/src/view/d3/hierarchy/configurablepivottreemap/ConfigurablePivotTreeMapComponent.js, packages/ext-web-components-kitchensink/src/view/main/MainComponent.html, packages/ext-web-components-kitchensink/src/view/trees/treereorder/TreeReorderComponent.html, packages/ext-web-components-kitchensink/src/view/trees/treereorder/TreeReorderComponent.js
Hello Marc,
In this PR, web components kitchensink bugs have been resolved.
Kindly review and merge.
Thanks,
Palak
=> EWC-4-KS-Resolved WebComponents Kitchensink bugs.

packages/ext-web-components-kitchensink/src/view/components/layouts/cardlayout/CardLayoutComponent.js, packages/ext-web-components-kitchensink/src/view/components/panels/resizablehandle/ResizableHandleComponent.html, packages/ext-web-components-kitchensink/src/view/components/panels/timepanel/TimePanelComponent.html, packages/ext-web-components-kitchensink/src/view/components/panels/timepanel/TimePanelComponent.js, packages/ext-web-components-kitchensink/src/view/pivotgrids/datachanges/DataChangesComponent.html
Under this PR following components IE bugs are fixed:
1. CardLayoutComponent
2. ResizableHandleComponent
3. TimePanelComponent
4. DataChangesComponent
=> EWC-9-Latest-IE-Component-Bug-Fixes | component IE bugs fixed

packages/ext-web-components-kitchensink/src/view/components/layouts/cardlayout/CardLayoutComponent.js, packages/ext-web-components-kitchensink/src/view/components/panels/basicpanel/BasicPanelComponent.html
Hi Marc
Under this PR, CardLayout component's action control bug and BasicPanel component visibility bug are fixed now. Kindly review.
Thanks
Pooja
=> EWC-9-Latest-IE-Component-Bug-Fixes | cardLayout and basicpanel bug fix

api-docs/core/src/Widget.js, api-docs/modern/modern/src/BreadcrumbBar.js, api-docs/modern/modern/src/panel/Time.js
Hi Mar,
This PR has some required changes in API Docs. Kindly Review.
Thanks, Medha.
=> EWC-5| API DOCS|Changes Update

api-docs/modern/modern/src/field/CheckboxGroup.js, api-docs/modern/modern/src/field/Panel.js, api-docs/modern/modern/src/field/Text.js
Hi Marc,
In this PR we have fixes the API Doc bugs occurred in Ext-Web-Components.
Please review.
Thanks,
Suresh
=> EWC-5-KS-API-Docs | Fixed the API Docs issue in Web Components

packages/ext-web-components-kitchensink/src/view/components/gauges/needlegauge/NeedleGaugeComponent.html, packages/ext-web-components-kitchensink/src/view/components/touchevents/TouchEventsComponent.js
In this PR,
Two KS bugs are resolved.
Kindly Review
Rahul Garg
=> EWC-4-KS | All browser bug

packages/ext-web-components-kitchensink/src/view/grids/advancedfeatures/selectandcopy/SelectAndCopyComponent.html, packages/ext-web-components-kitchensink/src/view/grids/advancedfeatures/selectandcopy/SelectAndCopyComponent.js, packages/ext-web-components-kitchensink/src/view/pivotgrids/collapsible/CollapsibleComponent.js, packages/ext-web-components-kitchensink/src/view/pivotgrids/exporterplugin/ExporterPluginComponent.js
Hi Marc
Under this PR, ext-web-component Kitchensink Edge Issues of following components are fixed:
1. Select and Copy 
2. Collapsible
3. Exporter Plugin
Thanks
Pooja
=> EWC-4-KS-EdgeIssues | KS Edge Issues resolved.

packages/ext-web-components-kitchensink/ext-web-components/packages/theme-kitchensink/sass/etc/examples-font.scss, packages/ext-web-components-kitchensink/src/menu.js
In this PR, Grid Row DND icon is fixed.
Kindly Review
Rahul Garg
=> EWC-4-KS Row DND Icon is fixed.

packages/ext-web-components-kitchensink/src/view/components/gauges/needlegauge/NeedleGaugeComponent.html
In this PR, An open bug of Needle Gauge is fixed as per the bug report ticket EXTJS-27853.
Kindly Review
Rahul Garg
=> EWC-4 Needle gauge issue is now resolved.

packages/ext-web-components-conference-app/src/view/about/AboutComponent.html, packages/ext-web-components-conference-app/src/view/schedule/ScheduleComponent.html, packages/ext-web-components-conference-app/src/view/schedule/ScheduleComponent.js, packages/ext-web-components-conference-app/src/view/speakers/SpeakersComponent.html
As per the ticket EXTJS-28599, Out of four issues, two are resolved and one of them is a build issue happening in Ext React and another one is not getting reproduced.
Kindly Review
Rahul Garg
=> EXTJS-28599 Conference App Issue.

packages/ext-web-components-kitchensink/src/view/calendar/timezonesupport/TimezoneSupportComponent.html, packages/ext-web-components-kitchensink/src/view/calendar/timezonesupport/TimezoneSupportComponent.js
Hi Marc,
This PR is focused on TimezoneSupportComponent.
Kindly review.
Thanks, Medha.
=> EWC-34-TimezoneSupport fixed

packages/ext-web-components-tests/src/view/createChild/insertbetween/InsertBetweenComponent.js, packages/ext-web-components-tests/src/view/createChild/insertend/InsertEndComponent.js, packages/ext-web-components-tests/src/view/createChild/insertstart/InsertStartComponent.js
As per the ticket EWC-38 the test application is now fixed and running.
Kindly Review
Rahul Garg
=> EWC-38 Test application is now fixed as per new bridge.

packages/ext-web-components-kitchensink/src/view/d3/heatmap/pivotheatmap/PivotHeatmapComponent.html, packages/ext-web-components-kitchensink/src/view/d3/heatmap/pivotheatmap/PivotHeatmapComponent.js
In this PR, Orientation is used instead of device width.
Kindly Review
Rahul Garg
=> EWC-36 Orientation is now consumed and the fix is provided.

packages/ext-web-components-tests/src/app.js, packages/ext-web-components-tests/src/view/main/MainComponent.html, packages/ext-web-components-tests/src/view/main/MainComponent.js, packages/ext-web-components-tests/src/view/rel/reltooltip/RelTooltipComponent.html
In this PR, Changes are made as per the new modification inside the bridge.
Kindly Review
Rahul Garg
=> EWC 38 test check

packages/ext-web-components-kitchensink/src/index.html
New PR, With Dynamic consumption of the polyfill only for IE11.
Kindly Review
Rahul Garg
=> The polyfill is now inserted on the grounds using browser
